server:
    port: 8080

spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/

# ???? ? ??? ??? ???????? ????????, ??????? ???????? ???????? ???????
# ?? ?????-?????? ??????? ????, ????? ?????????, ??? ????????????? ????????.
# ? ??????? ?? ??????? ??? ?? ???????? ? ????? ?????????????.
#            routes:
#            - id: test_route # ?????????? ID ????????
#              uri: https://httpbin.org # ?????, ???? ??????????????
#              predicates:
#                - Path=/test/** # ???????: ???? ???? ??????? ?????????? ? /test/, ???????????? ???? ???????