server:
    port: 8080

spring:
    application:
        name: api-gateway
    cloud:
        gateway:
          server:
            webflux:
              routes:
                - id: user-service-route
                  uri: lb://user-service
                  predicates:
                      - Path=/api/v1/users/**, /api/v1/auth/**

                - id: catalog-service-route
                  uri: lb://catalog-service
                  predicates:
                      - Path=/api/v1/categories/**, /api/v1/products/**
logging:
    level:
        org.springframework.cloud.gateway: TRACE
        reactor.netty.http.client: TRACE