server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: user-service-route
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**, /api/v1/auth/**

            - id: catalog-service-route
              uri: lb://catalog-service
              predicates:
                - Path=/api/v1/categories/**, /api/v1/products/**

            - id: inventory-service-route
              uri: lb://inventory-service
              predicates:
                - Path=/api/v1/inventory/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: TRACE